### PR TITLE
feat: improvment to bot

### PR DESCRIPTION
**Pull request by xhayper**

### CODE REVIEW

**Comment by AlekEagle** [comment]
LGTM, let's get the input of @danii on this rq though.

**Review by AlekEagle — APPROVED** [review]
Read previous comment.

**Comment by funnycatgaming** [comment]
ok

**Review by WaviestBalloon — APPROVED** [review]
LGTM x2

**Comment by WaviestBalloon** [comment]
Now restart the bot and watch as it run 9 times faster!

**Review by danii — COMMENTED** [review]
Is it supposed to slant down like that?

**Comment by WaviestBalloon** [comment]
> Is it supposed to slant down like that?

It's a feature

**Pull request merged**
